crud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("data.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

data/urls.py
from django.urls import path
from .views import (
    login_user,
    logout_user,
    register_user,
    home,
    tambah_data,
    edit_data,
    hapus_data,
)

app_name = "data"
urlpatterns = [
    path("register/", register_user, name="register"),
    path("login/", login_user, name="login"),
    path("logout/", logout_user, name="logout"),
    
    path("", home, name="home"),
    path("tambah/", tambah_data, name="tambah_data"),
    path("edit/<int:pk>/", edit_data, name="edit_data"),
    path("hapus/<int:pk>/", hapus_data, name="hapus_data"),
]

data/models.py
from django.db import models
from django.utils.translation import gettext, gettext_lazy as _
from django.conf import settings

AUTH_USER_MODEL = getattr(settings, "AUTH_USER_MODEL")

# Create your models here.

def get_data_image_path(instance, filename):
    """Fungsi untuk mengembalikan image path.
    """
    import os.path
    return os.path.join("datas", instance.owner.username, filename)

class Data(models.Model):
    """Class ini mengimplementasikan field-field yang berada di tabel data.
    """
    owner = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(_("judul"), max_length=255)
    description = models.TextField(_("deskripsi"), blank=True)
    image = models.ImageField(_("gambar"), upload_to=get_data_image_path, blank=True, null=True)
    
    def __str__(self):
        """Fungsi untuk mengembalikan nama data.
        """
        return self.title

data/views.py
from django.shortcuts import render, redirect, get_list_or_404
from django.contrib.auth import authenticate, login, logout
from django.http import HttpRequest, HttpResponse, Http404
from django.contrib import messages
from django.core.files.storage import FileSystemStorage

from django.contrib.auth.models import User
from django.db import IntegrityError

from .models import Data
# Create your views here.

def login_user(request: HttpRequest) -> HttpResponse:
    """Handler untuk login user.
    """
    if request.user.is_authenticated:
        # Jika user terautentikasi maka akan diredirect ke home.
        return redirect("data:home")
    
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        
        # Mendapatkan autentikasi user
        user = authenticate(request, username=username, password=password)
        
        # Cek apakah user dengan username dan password adalah benar.
        if user is not None:
            login(request, user) # Menyimpan data user di dalam session.
            return redirect("data:home")
        else:
            messages.error(request, "Username atau katasandi yang anda masukkan salah.")
            return redirect("data:login")
    else:
        return render(request, "data/login.html")


def register_user(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        first_name = request.POST["first_name"]
        last_name = request.POST["last_name"]
        username = request.POST["username"]
        email = request.POST["email"]
        password1 = request.POST["password1"]
        password2 = request.POST["password2"]
        
        if password1 != password2:
            messages.info(request, "Harap masukkan katasandi yang sama.")
            return redirect("data:register")
        
        try:
            user = User(first_name=first_name, last_name=last_name, username=username, email=email)
            user.set_password(password2)
            user.save()
            messages.success(request, "Berhasil mendaftarkan satu akun.")
            return redirect("data:login")
        except IntegrityError:
            messages.error(request, "User dengan informasi ini sudah ada.")
            return redirect("data:register")
    else:
        return render(request, "data/register.html")
        

def logout_user(request: HttpRequest) -> HttpResponse:
    """Handler untuk logout user.
    """
    logout(request)
    return redirect("data:login")


def home(request: HttpRequest) -> HttpResponse:
    if not request.user.is_authenticated:
        # Jika user belum login atau terautentikasi.
        return redirect("data:login")
    
    data = Data.objects.filter(owner=request.user)
    return render(request, "data/home.html", {"data": data})

def tambah_data(request: HttpRequest) -> HttpResponse:
    if not request.user.is_authenticated:
        # Jika user belum login atau terautentikasi.
        return redirect("data:login")
    
    if request.method == "POST":
        title = request.POST["title"]
        description = request.POST["description"]
        image = request.FILES["image"]

        data = Data(owner=request.user, title=title, description=description, image=image)
        data.save()
        
        messages.success(request, "Berhasil menambahkan satu data.")
        return redirect("data:home")
    else:
        return render(request, "data/tambah.html")

def edit_data(request: HttpRequest, pk: int) -> HttpResponse:
    if request.method == "GET":
        try:
            data = Data.objects.get(pk=pk)
            return render(request, "data/edit.html", {"data": data})
        except Data.DoesNotExist:
            raise Http404("Data tidak ditemukan.")
    else:
        title = request.POST["title"]
        description = request.POST["description"]
        image = request.FILES["image"]
        try:
            data = Data.objects.get(pk=pk)
            data.title = title
            data.description = description
            data.image = image
            data.save()
            
            messages.success(request, "Berhasil memperbaharui data.")
            return redirect("data:home")
        except Data.DoesNotExist:
            raise Http404("Data tidak ditemukan.")


def hapus_data(request: HttpRequest, pk: int) -> HttpResponse:
    try:
        data = Data.objects.get(pk=pk)
        data.delete()
        messages.success(request, "Berhasil menghapus satu data.")
        return redirect("data:home")
    except Data.DoesNotExist:
        raise Http404("Data tidak ditemukan.")

data/templates/data/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    {% block content %}{% endblock content %}
</body>
</html>

data/templates/data/edit.html
{% extends "data/base.html" %}

{% block title%}
Edit Data
{% endblock title%}

{% block content%}
<h1>Edit Data</h1>

{% for message in messages %}
<p style="color: red;">{{ message }}</p>
{% endfor %}

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <label for="title">Judul</label>
    <input type="text" name="title" value="{{ data.title }}" required> <br>
    
    <label for="description">Deskripsi</label>
    <textarea name="description" id="" required>
{{ data.description }}
    </textarea><br>

    <label for="image">Gambar</label>
    <input type="file" accept="image/png; image/jpg; image/jpeg" name="image" required> <br>
    {% if data.image %}
    <span>Current: <a href="{{ data.image.url }}">image</a></span><br><br>
    {% endif %}

    <button type="submit">Edit</button>
</form>
{% endblock content %}

data/templates/data/home.html
{% extends "data/base.html" %}

{% block title%}
Pendaftaran Akun
{% endblock title%}

{% block content%}
<h1>Halo, {{ request.user.get_full_name }}</h1>
<a href="{% url 'data:logout' %}">Logout</a>

<br><br>
<a href="{% url 'data:tambah_data' %}">Tambah data</a>
<br><br>

{% for message in messages %}
<p style="color: red;">{{ message }}</p>
{% endfor %}

<br><br>

{% for data in data %}
<div style="padding: 5px 5px 2rem; border: 1px solid #000; width: 450px;">
    <h3 style="margin: 0;">{{ data.title }}</h3>
    <p style="margin: 0;">{{ data.description }}</p>
    {% if data.image %}
        <img src="{{ data.image.url }}" alt="{{ data.title }}" width="420" height="200" /><br>
    {% endif %}
    <a href="{% url 'data:edit_data' data.pk %}">Edit</a>
    <a href="{% url 'data:hapus_data' data.pk %}">Hapus</a>
</div>
{% endfor %}

{% endblock content %}

data/templates/data/login.html
{% extends "data/base.html" %}

{% block title%}
Pendaftaran Akun
{% endblock title%}

{% block content%}
<h1>Login Akun</h1>

{% for message in messages %}
<p style="color: red;">{{ message }}</p>
{% endfor %}

<form action="" method="post">
    {% csrf_token %}
    <label for="username">Username</label>
    <input type="text" name="username" required> <br>
    
    <label for="password">Kata sandi</label>
    <input type="password" name="password" required> <br>

    <button type="submit">Login</button>
</form>

<a href="{% url 'data:register' %}">Belum mempunyai akun, daftar disini.</a>
{% endblock content %}

data/templates/data/register.html
{% extends "data/base.html" %}

{% block title%}
Pendaftaran Akun
{% endblock title%}

{% block content%}
<h1>Pendaftaran Akun</h1>

{% for message in messages %}
<p style="color: red;">{{ message }}</p>
{% endfor %}

<form action="" method="post">
    {% csrf_token %}

    <label for="first_name">Nama depan</label>
    <input type="text" name="first_name" required> <br>
    
    <label for="last_name">Nama belakang</label>
    <input type="text" name="last_name" required> <br>

    <label for="username">Username</label>
    <input type="text" name="username" required> <br>

    <label for="email">Email</label>
    <input type="email" name="email" required> <br>
    
    <label for="password1">Kata sandi</label>
    <input type="password" name="password1" required> <br>

    <label for="password2">Konfirmasi kata sandi</label>
    <input type="password" name="password2" required> <br>

    <button type="submit">Daftar</button>
</form>

<a href="{% url 'data:login' %}">Sudah mempunyai akun, login disini.</a>
{% endblock content %}

data/templates/data/tambah.html
{% extends "data/base.html" %}

{% block title%}
Tambah Data
{% endblock title%}

{% block content%}
<h1>Tambah Data</h1>

{% for message in messages %}
<p style="color: red;">{{ message }}</p>
{% endfor %}

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <label for="title">Judul</label>
    <input type="text" name="title" required> <br>
    
    <label for="description">Deskripsi</label>
    <textarea name="description" id="" required></textarea><br>

    <label for="image">Gambar</label>
    <input type="file" accept="image/png; image/jpg; image/jpeg" name="image" required> <br>

    <button type="submit">Tambah</button>
</form>
{% endblock content %}